steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.web'
      - '--build-arg'
      - 'VITE_API_URL=${_VITE_API_URL}'
      - '--build-arg'
      - 'VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}'
      - '--build-arg'
      - 'VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}'
      - '--build-arg'
      - 'VITE_GOOGLE_AI_KEY=${_VITE_GOOGLE_AI_KEY}'
      - '--build-arg'
      - 'VITE_GOOGLE_CLIENT_ID=${_VITE_GOOGLE_CLIENT_ID}'
      - '--build-arg'
      - 'VITE_GOOGLE_API_KEY=${_VITE_GOOGLE_API_KEY}'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/meishi:$BUILD_ID'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/meishi:$BUILD_ID'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'meishi'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/meishi:$BUILD_ID'
      - '--region'
      - 'asia-northeast1'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _VITE_API_URL: 'https://meishi-api-270124753853.asia-northeast1.run.app'
  _VITE_SUPABASE_URL: 'https://avakiygdyafqjrhlvbjg.supabase.co'
  _VITE_SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2YWtpeWdkeWFmcWpyaGx2YmpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5ODAzOTIsImV4cCI6MjA4OTU1NjM5Mn0.6X_9qlsrQSXx9eSKZQ3k0bqT2CM083L_NDsiSLaolOI'
  _VITE_GOOGLE_AI_KEY: 'AIzaSyB2VhNoNkARnygteXILsYBaQnPIIkmLRP8'
  _VITE_GOOGLE_CLIENT_ID: '270124753853-u1hjecajdni1e0t1s5dpr5hqo7eah9oa.apps.googleusercontent.com'
  _VITE_GOOGLE_API_KEY: 'AIzaSyCjjLXhUo0bl1EALyYAq5PZS8DiQw14X88'
